[package]
name = "pre_req"
version = "0.1.0"
edition = "2024"

[dependencies]
axum = "0.7"
serde = {version = "1.0", features = ["derive"]}
serde_json = "1.0.140"
tokio = { version = "1.0", features = ["full"] }
